### ISSUE TITLE
Update style_loader_tag, fix offset 0 issue

### ISSUE THREAD

**Issue by cabgfx** [cabgfx/wpbp-theme#4]
Since WP 5.x, you'll get a

`PHP Notice:  Undefined offset: 0 in /Users/Cab/Sites/Clients/ua-landing/wp-content/themes/wpbp-theme/lib/cleanup.php on line 96`

This is caused by `roots_clean_style_tag` in `lib/cleanup.php`.
The purpose of this is to output clean `<link rel="stylesheet">` tags in `wp_head`, and as such should be updated, since it's useful.

## Todo

- [x] Determine if the purpose of this is still needed
- [ ] ~~Update regex, to avoid the missing `[0]` index~~
- [ ] ~~Port changes from https://github.com/roots/soil/blob/main/src/Modules/CleanUpModule.php#L268~~

## Temporary workaround

Simply remove these lines, and WP will fall back to its default, slightly-less-clean output of stylesheet `<link>`s.

```
/**
 * Clean up output of stylesheet <link> tags
 */
function roots_clean_style_tag($input) {
  preg_match_all("!<link rel='stylesheet'\s?(id='[^']+')?\s+href='(.*)' type='text/css' media='(.*)' />!", $input, $matches);
  // Only display media if it is meaningful
  $media = $matches[3][0] !== '' && $matches[3][0] !== 'all' ? ' media="' . $matches[3][0] . '"' : '';
  return '<link rel="stylesheet" href="' . $matches[2][0] . '"' . $media . '>' . "\n";
}
add_filter('style_loader_tag', 'roots_clean_style_tag');
